UNFV.Presentation/Models/Area/AreaPaginateModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UNFV.Presentation.Models.Area
{
    public class AreaPaginateModel
    {
        public string descripcion { get; set; }
        public string codigoescuela { get; set; }
        public string page { get; set; }
        public string size { get; set; }
    }
}

UNFV.Presentation/Models/Area/CreateAreaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UNFV.Presentation.Models.Area
{
    public class CreateAreaModel
    {
        public decimal? CodigoArea{ get; set; }
        public decimal CodigoEscuela{ get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
    }
}

UNFV.Presentation/Controllers/AreaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using UNFV.Presentation.Models.Area;
using Negocio;
using Entidad.Repositorio.Models;

namespace UNFV.Presentation.Controllers
{
    public class AreaController : Controller
    {
        public AreaController()
        {

        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        public IActionResult AreaDetail()
        {
            return View();
        }
        [AllowAnonymous]
        public async Task<IActionResult> GetAllAreaPaginate(string AreaPaginateModel)
        {
            try
            {
                AreaPaginateModel ObjAreaPaginate =
                    Newtonsoft.Json.JsonConvert.DeserializeObject<AreaPaginateModel>(AreaPaginateModel);

                AreaNG NArea = new AreaNG();
                int codigo_escuela = 0;
                if (ObjAreaPaginate.codigoescuela != "")
                {
                    codigo_escuela = Convert.ToInt32(ObjAreaPaginate.codigoescuela);
                }

                var result = await NArea.GetAllAreaPaginate(ObjAreaPaginate.descripcion, codigo_escuela, ObjAreaPaginate.page, ObjAreaPaginate.size);
                return Ok(result);
            }
            catch (Exception ex)
            {
                return BadRequest(ex);
            }
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> CreateArea(string model)
        {
            AreaNG NArea = new AreaNG();
            CreateAreaModel oCreateAreaModel = Newtonsoft.Json.JsonConvert.DeserializeObject<CreateAreaModel>(model);
            Area objArea = new Area();
            objArea.CodigoArea = Convert.ToInt32(oCreateAreaModel.CodigoArea);
            objArea.CodigoEscuela = Convert.ToInt32(oCreateAreaModel.CodigoEscuela);
            objArea.Descripcion = oCreateAreaModel.descripcion;
            objArea.Habilitado = true;
            var area = await NArea.InsertArea(objArea);
            return Ok(area);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> GetAreaById(string areaId)
        {
            AreaNG NArea = new AreaNG();
            var result = await NArea.GetAreaById(Convert.ToDecimal(areaId));
            return Ok(result);
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> ChangeStatusArea(string model)
        {
            AreaNG NArea = new AreaNG();
            CreateAreaModel oCreateAreaModel = Newtonsoft.Json.JsonConvert.DeserializeObject<CreateAreaModel>(model);
            Area objArea = new Area();
            objArea.CodigoArea = Convert.ToInt32(oCreateAreaModel.CodigoArea);
            if (oCreateAreaModel.estado == "Activo")
            {
                objArea.Habilitado = false;
            }
            else
            {
                objArea.Habilitado = true;
            }
            var area = await NArea.ChangeStatusArea(objArea);
            return Ok(area);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> GetAllEscuela()
        {
            AreaNG NArea = new AreaNG();
            var result = await NArea.GetAllEscuela();
            return Ok(result);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> GetAllArea()
        {
            AreaNG NArea = new AreaNG();
            var result = await NArea.GetAllArea();
            return Ok(result);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> GetAllFacultad()
        {
            AreaNG NArea = new AreaNG();
            var result = await NArea.GetAllFacultad();
            return Ok(result);
        }
    }
}

UNFV.Presentation/Views/Area/AreaDetail.cshtml
@section Styles {
    <link rel="stylesheet" href="~/vendor/select2/dist/css/select2.min.css">
    <link href="~/vendor/daterangepicker/daterangepicker.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/vendor/flatpickr/dist/flatpickr.min.css">
    @*<link rel="stylesheet" href="https://unpkg.com/izitoast/dist/css/iziToast.min.css">*@
    <link rel="stylesheet" href="~/vendor/izitoast/css/iziToast.min.css">
    <link rel="stylesheet" href="~/vueJS/librerias/waitMe-spinner/easy-loading.css" />
    <style>
        .table thead th {
            text-transform: none !important;
        }

        .turned-off {
            background-color: rgba(19,33,68,.1) !important;
            color: #132144 !important
        }

        .turned-off-span {
            color: #132144 !important
        }

        .turned-on {
            color: #fff !important;
            background-color: #002f87 !important;
        }

        .turned-on-span {
            color: #002f87 !important;
        }

        .truncateText {
            overflow: hidden;
            white-space: nowrap;
            text-overflow: ellipsis;
        }

        [v-cloak] {
            display: none
        }

        .video-container {
            position: relative;
            padding-bottom: 56.25%;
            padding-top: 30px;
            height: 0;
            overflow: hidden;
        }

            .video-container iframe, .video-container object, .video-container iframe embed, .video-container iframe img {
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
            }
    </style>
}


<div class="content container-fluid" id="CreateCompleteArea" v-cloak-render>
    <div class="col-sm mb-2 mb-sm-0">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadcrumb-no-gutter">
                <li class="breadcrumb-item active"><a asp-action="Index" asp-controller="Area"> Áreas</a></li>
                <li class="breadcrumb-item active">{{areaId === 0 ? 'Registrar área' : 'Detalle del área'}}</li>
            </ol>
        </nav>
    </div>
    <div class="card">
        <div class="card-header justify-content-center justify-content-sm-between align-items-sm-center">
            <div class="col-sm p-0">
                <div class="d-flex justify-content-center justify-content-sm-start align-items-center ">
                    <h4 class="m-0">{{areaId === 0 ? 'Registrar área' : 'Detalle del área'}}</h4>
                </div>
            </div>
            <div class="col-sm-auto p-0" v-if="areaId !== 0">
                <div class="d-flex justify-content-center justify-content-sm-end">
                    <h4 class="m-0 text-primary font-weight-bold"> Nro. {{areaId}}</h4>
                </div>
            </div>
        </div>
        <div class="card-body">
            <!-- Body -->
            <div class="modal-body">


                <!-- Step Form -->
                <form class="js-step-form"
                      data-hs-step-form-options='{
                                "progressSelector": "#createProjectStepFormProgress",
                                "stepsSelector": "#createProjectStepFormContent",
                                "endSelector": "#createProjectFinishBtn",
                                "isValidate": false
                      }' data-vv-scope="formCreateArea">
                    <!-- Step -->
                    <ul id="createProjectStepFormProgress" class="js-step-progress step step-sm step-icon-sm step-inline step-item-between mb-7">
                        <li class="step-item">
                            <a class="step-content-wrapper" href="javascript:;">
                                <span class="step-icon step-icon-soft-dark" v-bind:class="'turned-on'">1</span>
                                <div class="step-content">
                                    <span class="step-title" v-bind:class="'turned-on-span'">Datos principales</span>
                                </div>
                            </a>
                        </li>
                    </ul>

                    <div id="createProjectStepFormContent">

                        <div id="createContratante" class="active">

                            <div class="form-group">
                                <div class="row">

                                    <div class="col-sm-6">
                                        <label class="input-label">Descripción</label>
                                        <input type="text"
                                               class="form-control"
                                               name="address"
                                               v-model="descripcion"
                                               v-validate="'required'"
                                               v-bind:class="{'is-invalid': errors.has('formCreateClient.descripcion') }" />
                                        <span v-show="errors.has('formCreateArea.descripcion')" class="text-danger text-left">{{errors.first('formCreateArea.descripcion')}}</span>
                                    </div>

                                    <div class="col-md-3 col-sm-12">
                                        <div class="form-group mb-2">
                                            <label class="input-label mb-1">Escuela</label>

                                            <select class="js-select2-custom custom-select" size="1" style="opacity: 0;"
                                                    data-hs-select2-options='{
                                                  "minimumResultsForSearch": "Infinity"
                                                  }'
                                                    ref="codigoescuela"
                                                    id="codigoescuela"
                                                    name="codigoescuela"
                                                    v-model="codigoescuela"
                                                    v-select="codigoescuela">
                                                <option value="">Todos</option>
                                                <option v-for="item in escuelaList" :value="item.CodigoEscuela" selected>
                                                    {{item.Descripcion}}
                                                </option>
                                            </select>
                                            <span v-show="errors.has('formCreateArea.codigoescuela')" class="text-danger text-left">{{errors.first('formCreateArea.codigoescuela')}}</span>
                                        </div>
                                    </div>

                                </div>
                            </div>

                            <div class="d-flex justify-content-end ml-auto">
                                <button id="createProject" type="button" class="btn btn-primary" v-on:click="save">Guardar</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>


        </div>
    </div>



</div>

@section Plugins {
    <script src="~/vendor/select2/dist/js/select2.full.min.js"></script>
    <script src="~/vendor/daterangepicker/moment.min.js"></script>
    <script src="~/vendor/hs-step-form/dist/hs-step-form.min.js"></script>
    <script src="~/vendor/flatpickr/dist/flatpickr.min.js"></script>
    <script src="~/vueJS/librerias/waitMe-spinner/easy-loading.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.12.5/dist/sweetalert2.all.min.js"></script>
    @*<script src="https://unpkg.com/izitoast/dist/js/iziToast.min.js" type="text/javascript"></script>*@
    <script src="~/vendor/izitoast/js/iziToast.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/node-uuid/1.4.7/uuid.min.js"></script>

}

@section Scripts {
    <script src="~/js/Area/CreateArea.js" asp-append-version="true"></script>
}

@section documentOnReady {



    // initialization date
    $('.js-flatpickr').each(function () {
    $.HSCore.components.HSFlatpickr.init($(this));
    })


    // initialization of step form
    $('.js-step-form').each(function () {
    var stepForm = new HSStepForm($(this), {
    finish: function() {
    $("#createProjectStepFormProgress").hide();
    $("#createProjectStepFormContent").hide();
    $("#createProjectFinishBtn").show();
    }
    }).init();
    });

    // initialization of quick view popover
    $('#newProjectPopover').popover('show');

    $(document).on('click', '#closeNewProjectPopover' , function() {
    $('#newProjectPopover').popover('dispose');
    });


    // initialization select
    $('.js-select2-custom').each(function () {
    var select2 = $.HSCore.components.HSSelect2.init($(this));
    });



}

UNFV.Presentation/Views/Area/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles {
    <link rel="stylesheet" href="~/vendor/select2/dist/css/select2.min.css">
    <link href="~/vendor/daterangepicker/daterangepicker.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="https://unpkg.com/izitoast/dist/css/iziToast.min.css">*@
    <link rel="stylesheet" href="~/vendor/izitoast/css/iziToast.min.css">
    <link rel="stylesheet" href="~/vueJS/librerias/waitMe-spinner/easy-loading.css" />
    <style>
        .table thead th {
            text-transform: none !important;
        }

        .table-vigente, .table-vigente > td, .table-vigente > th {
            vertical-align: middle !important;
        }

        .table-suspension, .table-suspension > td, .table-suspension > th {
            background-color: #f2f89f;
            vertical-align: middle !important;
        }

            .table-suspension tbody + tbody, .table-suspension td, .table-suspension th, .table-suspension thead th {
                border-color: #e6f140;
            }

            .table-suspension, .table-suspension > td, .table-suspension > th {
                background-color: #f2f89f;
            }
    </style>
}

<div class="content container-fluid" id="Area" v-cloak-render>

    <div class="col-sm mb-2 mb-sm-0">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadcrumb-no-gutter">
                <li class="breadcrumb-item active">Área</li>
            </ol>
        </nav>
    </div>


    <div class="card">
        <div class="card-header justify-content-center justify-content-sm-between align-items-sm-center">
            <div class="col-sm p-0">
                <div class="d-flex justify-content-center justify-content-sm-start align-items-center ">
                    <h4 class="m-0">Mantenimiento del área</h4>
                </div>
            </div>
            <div class="col-sm-auto pr-2">
                <div class="d-flex justify-content-center justify-content-sm-end">
                    <button v-if="NamesRoles.some(x => x.Name === 'Vendedor EPS' || x.Name === 'Administrador' || x.Name === 'Agente Comercial')"
                            class="btn btn-primary btn-block btn-sm"
                            v-on:click="newArea">
                        <i class="tio-add"></i> Registrar área
                    </button>
                </div>
            </div>
        </div>
        <div class="card-body">

            <div class="row">
                <div class="col-md-4 col-sm-12">
                    <div class="form-group mb-2 sm">
                        <label class="input-label mb-1">Fecha de registro</label>
                        <input type="text" id="creationDate" class="js-daterangepicker form-control">
                    </div>
                </div>
                <div class="col-md-3 col-sm-12">
                    <div class="form-group mb-2 sm">
                        <label class="input-label mb-1">Descripción</label>
                        <input type="text" class="form-control" v-model="description">
                    </div>
                </div>
                <div class="col-md-3 col-sm-12">
                    <div class="form-group mb-2">
                        <label class="input-label mb-1">Escuela</label>

                        <select class="js-select2-custom custom-select" size="1" style="opacity: 0;"
                                data-hs-select2-options='{
                                                  "minimumResultsForSearch": "Infinity"
                                                  }'
                                ref="codigoescuela"
                                id="codigoescuela"
                                name="codigoescuela"
                                v-model="codigoescuela"
                                v-select="codigoescuela">
                            <option value="">Todos</option>
                            <option v-for="item in escuelaList" :value="item.CodigoEscuela" selected>
                                {{item.Descripcion}}
                            </option>
                        </select>
                    </div>
                </div>
                <div class="col-md-2 col-sm-12">
                    <div class="form-group mb-2">
                        <button id="BtnBuscarEmpresa" v-on:click="GetAllAreaPaginate(0)" class="btn btn-primary btn-block">
                            <i class="tio-search"></i> Buscar
                        </button>
                    </div>
                </div>
            </div>

            <div class="form-group row">

                <div class="col-sm-12">
                    <br />
                    <template>
                        <div class="table-responsive">
                            <b-table class="table table-hover"
                                     :fields="columnsTable"
                                     :items="salesList"
                                     :current-page="1"
                                     :per-page="perPage">

                                <template slot="opciones" slot-scope="row">

                                    <b-dropdown size="sm"
                                                boundary="window"
                                                variant="link"
                                                toggle-class="text-decoration-none"
                                                no-caret>
                                        <template slot="button-content">
                                            <i class="tio-settings text-secondary"></i>
                                        </template>
                                        <b-dropdown-item class="text-primary" v-on:click="areaDetail(row.item)">
                                            <i class="tio-search"></i>
                                            <a>Ver detalle </a>
                                        </b-dropdown-item>

                                        <b-dropdown-item class="text-primary"
                                                         v-on:click="ChangeStatusArea(row.item, 'enviado')"
                                                         v-if="(row.item.Estado == 'Activo')">
                                            <i class="tio-remove-from-trash"></i>
                                            <a>Deshabilitar</a>
                                        </b-dropdown-item>

                                        <b-dropdown-item class="text-primary"
                                                         v-on:click="ChangeStatusArea(row.item, 'enviado')"
                                                         v-if="(row.item.Estado != 'Activo')">
                                            <i class="tio-checkmark-square"></i>
                                            <a>Habilitar</a>
                                        </b-dropdown-item>
                                    </b-dropdown>
                                </template>
                            </b-table>
                        </div>
                        <b-row v-if="searching" class="vh-50 text-center" align-h="center">
                            <div class="text-center text-secondary my-2">
                                <b-spinner class="align-middle"></b-spinner>
                                <strong>Cargando...</strong>
                            </div>
                        </b-row>
                        <b-row v-if="withoutResults" class="vh-50 text-center" align-h="center">
                            <div class="text-center text-secondary my-2">
                                <strong>No hay resultados</strong>
                            </div>
                        </b-row>

                        <hr class="my-2" />

                        <b-row class="row justify-content-center justify-content-sm-between align-items-sm-center">

                            <div class="col-sm mb-2 mb-sm-0">
                                <div class="d-flex justify-content-center justify-content-sm-start align-items-center">
                                    <span class="mr-2">Mostrar:</span>
                                    <select id="datatableEntries"
                                            class="js-select2-custom"
                                            data-hs-select2-options='{
                                            "minimumResultsForSearch": "Infinity",
                                            "customClass": "custom-select custom-select-sm custom-select-borderless",
                                            "dropdownAutoWidth": true,
                                            "width": true
                                          }'
                                            v-model="perPage"
                                            v-select="perPage"
                                            v-on:change="GetAllAreaPaginate()">
                                        <option value="10">10</option>
                                        <option value="20">20</option>
                                        <option value="30">30</option>
                                    </select>
                                    <span class="text-secondary mr-2">registros</span>
                                </div>
                            </div>

                            <div class="col-sm-auto">
                                <div class="d-flex justify-content-center justify-content-sm-end">
                                    <b-pagination :total-rows="totalRows" :per-page="perPage" v-model="currentPage" v-on:change="GetAllAreaPaginate">
                                    </b-pagination>
                                </div>
                            </div>
                        </b-row>
                    </template>
                </div>
            </div>
        </div>
    </div>

    

    <advanced-create-plotpreaffiliation v-bind:Data="SaleData"></advanced-create-plotpreaffiliation>
    <placement-change-status v-on:click="GetAllAreaPaginate" v-bind:Data="SaleData"></placement-change-status>
</div>


@section Plugins {

    <script src="~/vendor/select2/dist/js/select2.full.min.js"></script>
    <script src="~/vendor/daterangepicker/moment.min.js"></script>
    <script src="~/vendor/daterangepicker/daterangepicker.js"></script>
    <script src="~/vendor/hs-step-form/dist/hs-step-form.min.js"></script>
    <script src="~/vendor/hs-file-attach/dist/hs-file-attach.js"></script>
    <script src="~/vueJS/librerias/waitMe-spinner/easy-loading.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.12.5/dist/sweetalert2.all.min.js"></script>
    @*<script src="https://unpkg.com/izitoast/dist/js/iziToast.min.js" type="text/javascript"></script>*@
    <script src="~/vendor/izitoast/js/iziToast.min.js" type="text/javascript"></script>
}

@section Scripts {

    <script src="~/js/Area/Area.js" asp-append-version="true"></script>
}

@section documentOnReady {

    // initialization select
    $('.js-select2-custom').each(function () {
    var select2 = $.HSCore.components.HSSelect2.init($(this));
    });

    // initialization of daterangepicker
    $('.js-daterangepicker').each(function () {
    var d = $.HSCore.components.HSDaterangepicker.init($(this));
    });


    var dateNow = new Date();
    var initDate = new Date(dateNow.getFullYear(), dateNow.getMonth() - 2, 1);
    var endDate = new Date(dateNow.getFullYear(), dateNow.getMonth() + 1, 0);

    $("#creationDate").daterangepicker({
    "startDate": initDate,
    "endDate": endDate,
    locale: {
    format: 'DD/MM/YYYY',
    applyLabel: 'Aplicar',
    cancelLabel: 'Limpiar',
    fromLabel: 'Desde',
    toLabel: 'Hasta',
    customRangeLabel: 'Seleccionar rango',
    daysOfWeek: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
    monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
    'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre',
    'Diciembre'],
    firstDay: 1
    }
    });



    // initialization of step form
    $('.js-step-form').each(function () {
    var stepForm = new HSStepForm($(this), {
    finish: function() {
    $("#createProjectStepFormProgress").hide();
    $("#createProjectStepFormContent").hide();
    $("#createProjectStepSuccessMessage").show();
    }
    }).init();
    });

    // initialization of quick view popover
    $('#newProjectPopover').popover('show');

    $(document).on('click', '#closeNewProjectPopover' , function() {
    $('#newProjectPopover').popover('dispose');
    });

    $('#newRechazoModal').on('show.bs.modal', function() {
    $('#newProjectPopover').popover('dispose');
    });

    // INITIALIZATION OF CUSTOM FILE
    // =======================================================
    $('.js-file-attach').each(function () {
    var customFile = new HSFileAttach($(this)).init();
    });


}